version: '3.8'
volumes:
  pg_data:
services:
  pg_db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432