# Generated by Django 4.2.3 on 2023-07-17 13:36

from django.db import migrations, models
import django.db.models.deletion
import votings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("second_name", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "photo",
                    models.ImageField(upload_to=votings.models.character_image_path),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CharacterVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="votings.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("max_votes", models.IntegerField(blank=True, null=True)),
                (
                    "characters",
                    models.ManyToManyField(
                        through="votings.CharacterVote", to="votings.character"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execute_at", models.DateTimeField()),
                ("e_mail", models.EmailField(default=None, max_length=254, null=True)),
                ("task_id", models.CharField(max_length=100)),
                (
                    "xlsx",
                    models.FileField(default=None, null=True, upload_to="reports/"),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="votings.voting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reports",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.AddField(
            model_name="charactervote",
            name="voting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="votings.voting",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactervote",
            constraint=models.UniqueConstraint(
                fields=("voting", "character"), name="unique_voting_character"
            ),
        ),
    ]
