# Generated by Django 4.2.3 on 2023-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0003_alter_voting_max_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="max_votes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
