# Generated by Django 4.2.3 on 2023-07-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0004_alter_voting_max_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.IntegerField(),
        ),
    ]
