# Generated by Django 4.2.3 on 2023-07-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0005_alter_character_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="character",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="last_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="second_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
