# Generated by Django 4.2.3 on 2023-07-09 04:02

from django.db import migrations, models
import votings.models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0006_alter_character_age_alter_character_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="photo",
            field=models.ImageField(upload_to=votings.models.character_image_path),
        ),
    ]
