# Generated by Django 4.2.3 on 2023-07-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votings", "0008_alter_voting_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="voting",
            name="characters",
            field=models.ManyToManyField(
                through="votings.CharacterVote", to="votings.character"
            ),
        ),
    ]
